# Site
name: "Mum and Crafts"
title: "Mum and Crafts"
description: "What can be better than spending your time with kids and family. It's the perfect time to become young again and do so crafty projects."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'

google_analytics: 'UA-157985851-1'
include: ["_pages"]
permalink: /:title/

collections:
  blog_categories:
    output: true
  blog_tags:
    output: true


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag


# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

exclude: [Gemfile, Gemfile.lock]
